version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    ports:
      - ${ROOM_DATABASE_PORT:-1433}:1433
    environment:
      ACCEPT_EULA: "Y" 
      SA_PASSWORD: ${ROOM_DATABASE_PASSWORD} 
      MSSQL_PID: "Express"
    volumes:
      - db:/var/opt/mssql/data 

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
