//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rooms.Domain.Validations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rooms.Domain.Validations.ValidationMessagesResource", typeof(ValidationMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be at least {0} years old..
        /// </summary>
        public static string AGE_LEAST_MESSAGE {
            get {
                return ResourceManager.GetString("AGE_LEAST_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be less than {0} years old..
        /// </summary>
        public static string AGE_LESS_MESSAGE {
            get {
                return ResourceManager.GetString("AGE_LESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The age group cannot be undefined..
        /// </summary>
        public static string AGE_UNDEFINED_MESSAGE {
            get {
                return ResourceManager.GetString("AGE_UNDEFINED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The {0} cannot be in the future.
        /// </summary>
        public static string CANNOT_BE_FUTURE_MESSAGE {
            get {
                return ResourceManager.GetString("CANNOT_BE_FUTURE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be empty..
        /// </summary>
        public static string EMPTY_MESSAGE {
            get {
                return ResourceManager.GetString("EMPTY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be have length equal to {1}..
        /// </summary>
        public static string EQUAL_LENGTH_MESSAGE {
            get {
                return ResourceManager.GetString("EQUAL_LENGTH_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be greater than {1}..
        /// </summary>
        public static string GREATER_MESSAGE {
            get {
                return ResourceManager.GetString("GREATER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be null..
        /// </summary>
        public static string NULL_MESSAGE {
            get {
                return ResourceManager.GetString("NULL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} cannot be null or empty..
        /// </summary>
        public static string NULL_OR_EMPTY_MESSAGE {
            get {
                return ResourceManager.GetString("NULL_OR_EMPTY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of seats (0) cannot exceed the room&apos;s capacity of {1}..
        /// </summary>
        public static string SEAT_CAPACITY_EXCEED_MESSAGE {
            get {
                return ResourceManager.GetString("SEAT_CAPACITY_EXCEED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be smaller than {1}..
        /// </summary>
        public static string SMALLER_MESSAGE {
            get {
                return ResourceManager.GetString("SMALLER_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date must be earlier than the end date..
        /// </summary>
        public static string START_DATE_EARLIER_MESSAGE {
            get {
                return ResourceManager.GetString("START_DATE_EARLIER_MESSAGE", resourceCulture);
            }
        }
    }
}
