CREATE TABLE [Persons]
(
    [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL,
    [FirstName] NVARCHAR(50) NOT NULL,
    [LastName] NVARCHAR(50) NOT NULL,
    [BirthDate] DATETIME2 NOT NULL,
    [SeatId] UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY([SeatId]) REFERENCES [Seats]([Id])
);
