CREATE TABLE [Seats]
(
    [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL,
    [Name] NVARCHAR(3) NOT NULL,
    [RoomId] UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY([RoomId]) REFERENCES [Rooms]([Id])
);
